import Navigation from "./components/navigation/navigation";
import "./styles/globals.css";

import Link from "next/link";

export const metadata = {
   title: "Smart Buy",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body >
            <Navigation/>
            {children}
         </body>
      </html>
   );
}
