import Footer from "./components/footer/footer";
import Navigation from "./components/navigation/navigation";
import { IsAuthorized } from "./identity/authentication/authSync";
import AuthorizationProvider from "./lib/contexts/AuthorizationContext";
import "./styles/globals.css";

export const metadata = {
   title: "Smart Buy",
   description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
   // let loggedIn = await IsAuthorized();

   return (
      <html lang="en">
         <body>

               <>
                  <Navigation />
                  {children}
                  <Footer />
               </>

         </body>
      </html>
   );
}
