import Footer from "./components/footer/footer";
import Navigation from "./components/navigation/navigation";
import Sidebar from "./components/sidebar/sidebar";
import "./styles/globals.css";

export const metadata = {
   title: "Smart Buy",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body>
            <Navigation />
            {children}
            <Footer />
         </body>
      </html>
   );
}
